# Generated by Django 6.0.1 on 2026-01-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                ("owner", models.CharField(max_length=150)),
                ("total_acreage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("planted_date", models.DateField()),
                ("harvest_date", models.DateField(blank=True, null=True)),
                (
                    "expected_yield",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected yield in bushels",
                        max_digits=10,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="farmwise.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-planted_date"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("equipment", "Equipment"),
                            ("land", "Land"),
                            ("livestock", "Livestock"),
                            ("building", "Building"),
                            ("vehicle", "Vehicle"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="farmwise.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-current_value"],
            },
        ),
        migrations.CreateModel(
            name="WealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_crop_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_asset_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wealth_records",
                        to="farmwise.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("farm", "date")},
            },
        ),
    ]
